services:
  - type: web
    name: streamlit-app
    env: python
    repo: https://github.com/<akarshvante>/<DOC_QA_System>
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
